import React from 'react';
import Svg, { Path } from 'react-native-svg';
import {
  si1password,
  siApple,
  siAsana,
  siAudible,
  siCrunchyroll,
  siDiscord,
  siDoordash,
  siDropbox,
  siDuolingo,
  siEpicgames,
  siEvernote,
  siExpressvpn,
  siFigma,
  siGithub,
  siGrammarly,
  siHbomax,
  siHeadspace,
  siInstacart,
  siLyft,
  siMedium,
  siNetflix,
  siNordvpn,
  siNotion,
  siParamountplus,
  siPatreon,
  siPeloton,
  siPlaystation,
  siShopify,
  siSoundcloud,
  siSpotify,
  siSquarespace,
  siSteam,
  siStrava,
  siTiktok,
  siTinder,
  siTrello,
  siTwitch,
  siUber,
  siVimeo,
  siWix,
  siX,
  siYoutube,
  siZoom
} from 'simple-icons';

export function BrandIcon({ path, color, size = 32 }: { path: string, color: string, size?: number }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24">
      <Path d={path} fill={color} />
    </Svg>
  );
}

export const POPULAR_APPS = [
  { id: 'netflix', name: 'Netflix', icon: siNetflix },
  { id: 'spotify', name: 'Spotify', icon: siSpotify },
  { id: 'apple', name: 'Apple One', icon: siApple },
  { id: 'youtube', name: 'YouTube', icon: siYoutube },
  { id: 'max', name: 'HBO Max', icon: siHbomax },
  { id: 'paramount', name: 'Paramount+', icon: siParamountplus },
  { id: 'crunchyroll', name: 'Crunchyroll', icon: siCrunchyroll },
  { id: 'discord', name: 'Discord', icon: siDiscord },
  { id: 'twitch', name: 'Twitch', icon: siTwitch },
  { id: 'tiktok', name: 'TikTok', icon: siTiktok },
  { id: 'x', name: 'X (Twitter)', icon: siX },
  { id: 'tinder', name: 'Tinder', icon: siTinder },
  { id: 'soundcloud', name: 'SoundCloud', icon: siSoundcloud },
  { id: 'figma', name: 'Figma', icon: siFigma },
  { id: 'notion', name: 'Notion', icon: siNotion },
  { id: 'github', name: 'GitHub Copilot', icon: siGithub },
  { id: 'steam', name: 'Steam', icon: siSteam },
  { id: 'epicgames', name: 'Epic Games', icon: siEpicgames },
  { id: 'playstation', name: 'PS Plus', icon: siPlaystation },
  { id: 'dropbox', name: 'Dropbox', icon: siDropbox },
  { id: 'trello', name: 'Trello', icon: siTrello },
  { id: 'zoom', name: 'Zoom', icon: siZoom },
  { id: 'audible', name: 'Audible', icon: siAudible },
  { id: 'duolingo', name: 'Duolingo', icon: siDuolingo },
  { id: 'strava', name: 'Strava', icon: siStrava },
  { id: 'peloton', name: 'Peloton', icon: siPeloton },
  { id: 'vimeo', name: 'Vimeo', icon: siVimeo },
  { id: 'headspace', name: 'Headspace', icon: siHeadspace },
  { id: 'patreon', name: 'Patreon', icon: siPatreon },
  { id: 'asana', name: 'Asana', icon: siAsana },
  { id: 'evernote', name: 'Evernote', icon: siEvernote },
  { id: '1password', name: '1Password', icon: si1password },
  { id: 'expressvpn', name: 'ExpressVPN', icon: siExpressvpn },
  { id: 'nordvpn', name: 'NordVPN', icon: siNordvpn },
  { id: 'shopify', name: 'Shopify', icon: siShopify },
  { id: 'squarespace', name: 'Squarespace', icon: siSquarespace },
  { id: 'wix', name: 'Wix', icon: siWix },
  { id: 'uber', name: 'Uber One', icon: siUber },
  { id: 'lyft', name: 'Lyft Pink', icon: siLyft },
  { id: 'doordash', name: 'DashPass', icon: siDoordash },
  { id: 'instacart', name: 'Instacart+', icon: siInstacart },
  { id: 'grammarly', name: 'Grammarly', icon: siGrammarly },
  { id: 'medium', name: 'Medium', icon: siMedium },
];
